import { InterviewSession } from "../types/session";
import { AppConfig } from "../types/config";
import { TauriApi } from "../services/tauriApi";

/**
 * Format an entire interview session (transcripts, AI Q&A logs, and context)
 * into a clean, human-readable text document and trigger native file save.
 */
export const exportSessionAsTxt = async (
  session: InterviewSession,
  config?: AppConfig
): Promise<string | null> => {
  const lines: string[] = [];

  const divider = "=".repeat(72);
  const subDivider = "-".repeat(72);

  const title = session.title || "Untitled Interview";
  const dateStr = session.createdAt ? new Date(session.createdAt).toLocaleString() : new Date().toLocaleString();
  const role = session.role || config?.target_role || "Candidate";
  const company = session.company || config?.company_name || "N/A";
  const transcriptsCount = session.transcripts?.length || 0;
  const aiLogsCount = session.aiLogs?.length || 0;

  lines.push(divider);
  lines.push(` GHOSTCUE AI INTERVIEW REPORT & TRANSCRIPT LOG`);
  lines.push(divider);
  lines.push(`Interview Title:  ${title}`);
  lines.push(`Target Role:      ${role}`);
  lines.push(`Company:          ${company}`);
  lines.push(`Recorded Date:    ${dateStr}`);
  lines.push(`Total Exchanges:  ${transcriptsCount}`);
  lines.push(`Saved AI Answers: ${aiLogsCount}`);
  lines.push(divider);
  lines.push("");

  // 1. LIVE CONVERSATION TRANSCRIPT
  lines.push(subDivider);
  lines.push(` 1. FULL CONVERSATION TRANSCRIPT (${transcriptsCount} Exchanges)`);
  lines.push(subDivider);

  if (session.transcripts && session.transcripts.length > 0) {
    session.transcripts.forEach((turn, idx) => {
      const speaker = turn.speaker === "Interviewer" ? "INTERVIEWER" : "CANDIDATE";
      const time = turn.timestamp ? `[${turn.timestamp}] ` : "";
      lines.push(`${idx + 1}. ${time}${speaker}:`);
      lines.push(`   ${turn.text}`);
      lines.push("");
    });
  } else {
    lines.push("No conversation transcripts recorded for this session.");
    lines.push("");
  }

  // 2. SAVED AI ANSWERS & QUESTIONS LOG
  lines.push(subDivider);
  lines.push(` 2. SAVED AI ANSWERS & SOLUTIONS (${aiLogsCount} Generated Answers)`);
  lines.push(subDivider);

  if (session.aiLogs && session.aiLogs.length > 0) {
    session.aiLogs.forEach((log, idx) => {
      const time = log.timestamp ? ` • ${log.timestamp}` : "";
      const model = log.model ? ` [${log.provider || "LLM"}/${log.model}]` : "";
      lines.push(`========================================================================`);
      lines.push(`AI ANSWER #${idx + 1} (${log.action.toUpperCase()}${time})${model}`);
      lines.push(`========================================================================`);
      if (log.query) {
        lines.push(`QUESTION / PROMPT:`);
        lines.push(`"${log.query}"`);
        lines.push("");
      }
      lines.push(`SUGGESTED ANSWER & CODE:`);
      lines.push(log.answer);
      lines.push("");
    });
  } else {
    lines.push("No AI suggestions generated during this session.");
    lines.push("");
  }

  // 3. CANDIDATE & PROJECT CONTEXT
  lines.push(subDivider);
  lines.push(` 3. INTERVIEW CONTEXT & CANDIDATE PROFILE`);
  lines.push(subDivider);

  if (session.jobDescription || config?.job_description) {
    lines.push(`[Job Description / Focus Topics]`);
    lines.push((session.jobDescription || config?.job_description || "").trim());
    lines.push("");
  }

  if (session.candidateResume || config?.candidate_resume) {
    lines.push(`[Candidate Resume / Strengths]`);
    lines.push((session.candidateResume || config?.candidate_resume || "").trim());
    lines.push("");
  }

  if (session.projectContext || config?.project_context) {
    lines.push(`[Project / Codebase Repository Context]`);
    const allDirs = session.projectDirectories && session.projectDirectories.length > 0
      ? session.projectDirectories
      : config?.project_directories && config.project_directories.length > 0
      ? config.project_directories
      : session.projectDirectory
      ? [session.projectDirectory]
      : config?.project_directory
      ? [config.project_directory]
      : [];

    if (allDirs.length > 0) {
      lines.push(`Connected Projects (${allDirs.length}):`);
      allDirs.forEach((d, i) => lines.push(`  ${i + 1}. ${d}`));
    }
    lines.push((session.projectContext || config?.project_context || "").trim());
    lines.push("");
  }

  lines.push(divider);
  lines.push(` End of Interview Report • Generated by GhostCue Stealth AI`);
  lines.push(divider);

  const fullText = lines.join("\n");
  const safeTitle = title.replace(/[^a-z0-9]/gi, "_").toLowerCase().slice(0, 30);
  const dateStamp = new Date().toISOString().slice(0, 10);
  const defaultFilename = `ghostcue_${safeTitle}_${dateStamp}.txt`;

  try {
    const savedPath = await TauriApi.saveTextFile(defaultFilename, fullText);
    return savedPath;
  } catch (err) {
    console.error("Failed to export interview session:", err);
    return null;
  }
};
